site_name: EMEAR Programmability CTF
nav:
  - Home: index.md
  - Enterprise Networking:
    - enterprise_networking/Introduction.md
    - Stages:
      - enterprise_networking/stages/stage-0.md
      - enterprise_networking/stages/stage-1.md
      - enterprise_networking/stages/stage-2.md
      - enterprise_networking/stages/stage-3.md
    - Hints:
      - enterprise_networking/hints/stage-0.md
      - enterprise_networking/hints/stage-1.md
      - enterprise_networking/hints/stage-2.md
      #- enterprise_networking/hints/stage-3.md
  - Collaboration:
    - collaboration/Introduction.md
    - Stages:
      - collaboration/stages/stage-0.md
      - collaboration/stages/stage-1.md
      - collaboration/stages/stage-2.md
      - collaboration/stages/stage-3.md
    - Hints:
      - collaboration/hints/stage-0.md
      - collaboration/hints/stage-1.md
      - collaboration/hints/stage-2.md
      - collaboration/hints/stage-3.md
  - Security:
    - security/Introduction.md
    - Stages:
      - security/stages/stage-0.md
      - security/stages/stage-1.md
      - security/stages/stage-2.md
      - security/stages/stage-3.md
    - Hints:
      - security/hints/stage-0.md
      - security/hints/stage-1.md
      - security/hints/stage-2.md
      - security/hints/stage-3.md
  #- Data Center:
  #  - data_center/Introduction.md
  #  - Stages:
  #    - data_center/stages/stage-0.md
  #    - data_center/stages/stage-1.md
  #    - data_center/stages/stage-2.md
  #    - data_center/stages/stage-3.md
  #  - Hints:
  #    - data_center/hints/stage-0.md
  #    - data_center/hints/stage-1.md
  #    - data_center/hints/stage-2.md
  #    - data_center/hints/stage-3.md
copyright: The Programmability CTF is a project by Marcel Neidinger and Frederic Wagner
theme:
  palette:
    primary: blue
  name: material
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg